services:
  - type: web
    name: prime-ai
    runtime: python

    buildCommand: |
      pip install uv
      uv sync

    startCommand: |
<<<<<<< HEAD
      uv run uvicorn server.main:app --host 0.0.0.0 --port $PORT
=======
      uv run uvicorn server.main:app --host 0.0.0.0 --port $PORT
>>>>>>> e867b26 (Prepare Render deployment)
